#!/usr/bin/env python
from __future__ import print_function
from os import listdir
from os.path import isfile, join


while True:
	x=raw_input(">>>")
	if x=="ls":
		for f in listdir("."):
			print(f, end=' ')
		print()
# onlyfiles = [f for f in listdir(".") ]

# print(onlyfiles)


